{% set name = "opentelemetry-instrumentation-requests" %}
{% set version = "0.37b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_requests-{{ version }}.tar.gz
  sha256: 180d48cc3b2c4542378ff0d6d6a2f09af982ac9c60ec70056f8f36385e84ea47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.37b0
    - opentelemetry-semantic-conventions ==0.37b0
    - opentelemetry-util-http ==0.37b0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  summary: OpenTelemetry requests instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
