{% set name = "opentelemetry-instrumentation-requests" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_requests-{{ version }}.tar.gz
  sha256: cc25ca78cfd41e0484970892ba15836a52e36c40da5442f75cf42791e20f96ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.42b0
    - opentelemetry-semantic-conventions ==0.42b0
    - opentelemetry-util-http ==0.42b0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-requests 
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  summary: OpenTelemetry requests instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
